print("Michael Jeff S. Sajul")
print("Dili, Gasan, Marinduque")
print("July 04, 2002")
print("")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("BSIT - 2A")
print("")
print("Playing online games.")
print("Playing basketball.")
print("Drawing.")
print("Watching anime and movies.")
print("Singing")
